name: "meal-planner"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    profiles:
      - service
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lambda:
    build:
      context: ./lambda
      target: meal-planner-api-development
    env_file: .env
    environment:
      - VIRTUAL_HOST=api.mealplanner.test
      - VIRTUAL_PORT=8080
    expose:
      - 8080
    profiles:
      - service
    volumes:
      - ./lambda:/usr/src/app

  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    profiles:
      - db
      - liquibase
      - service
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.23
    entrypoint: ["liquibase", "--defaultsFile=liquibase.properties"]
    command: ["update"]
    profiles:
      - liquibase
    volumes:
      - type: bind
        source: ./liquibase/liquibase.properties
        target: /liquibase/liquibase.properties
      - ./liquibase/changelog:/liquibase/changelog

volumes:
  db-data:
